language: android
dist: trusty
android:
  components:
    - build-tools-29.0.2
    - android-29
script:
  - gradle build assembleDebug
# Descomentar lo de abajo cuando tengamos claro dónde desplegar (gitflow)
# deploy:
#   provider: releases
#   api_key: "GITHUB OAUTH TOKEN"
#   file: app/builds/outputs/apk/release/app-release-unsigned.apk
#   skip_cleanup: true
#   on:
#     tags: true