language: android
dist: trusty
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
env:
  global:
    # Esperamos como máximo 10 min para que adb se conecte al emulador
    - ADB_INSTALL_TIMEOUT=20
    - SLAVE_AAPT_TIMEOUT=40
android:
  components:
    - build-tools-29.0.3
    - android-29
    - sys-img-armeabi-v7a-addon-google_apis-google-29
before_install:
  # Instalar calabash
  - rvm install 2.7.1
  - bundle install --jobs=3 --retry=3
before-script:
  # Dar permisos a gradle
  - chmod +x ./gradlew
  # Obtener rama actual en variable de entorno BRANCH
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  # Encendemos el emulador de android para los tests que lo necesiten
  - echo no | android create avd --force --name test --target android-29 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &
  - sleep 3 # Esperar a que la pantalla se desbloquee
  - ./gradlew clean connectedCheck assembleRelease -PdisablePreDex --continue --stacktrace

script:
  # Ejecutar tests siempre
  # Primero unitarios
  - "./gradlew test"
  # Calabash
  - calabash-android resign ./app/build/outputs/apk/release/app-release-unsigned.apk
  - calabash-android run ./app/build/outputs/apk/release/app-release-unsigned.apk
  # Si estamos en develop ejecutar sonar
  - if [ "$BRANCH" = "develop" ]; then ./gradlew sonarqube; fi
  # Si estamos en master desplegamos a GitHub Releases (hacemos un tag y deploy se encarga de desplegar)
  - if [ "$BRANCH" = "master" ]; then ./gradlew sonarqube; git config --global
    user.email "deploy@travis-ci.com"; git config --global user.name "Travis CI Deploy";
    export GIT_TAG=1.0.$TRAVIS_BUILD_NUMBER; git tag "$GIT_TAG" -a -m "Despliegue desde Travis con build numero $TRAVIS_BUILD_NUMBER";
    fi
deploy:
  provider: releases
  api_key:
    secure: K5qbU1o0uP0/toSDN1vQrMjNV2PTsIiqv/Jl5AXqRQq0MKKaeys5lzh3fqxti4ynFqyexWuwIsFvRg6fn7c92PVRAKieqVNFwgBcYqPtkerHf8vF63IpukNwdxhhAJ8WAQRbBUnmYPbhGJ314hQdQ6Hoc85hP/QQ0KIL4Q46aeCBU1qvpTpXWk0dQllSBm/mD2JNZBjp5izPUQVXBAVrtpBaoPb4hWkwSz8+oxCHmRDW4LGRZM25TkasW1aJuSpSSXQ5HkNAny8PlM22PT6Xs3yQyDrqPXzLYNOuYpNaGsyN5jUy6Jz2MSNk8x5V3K5r2Y/17V/72+mm3pA1DIYWf0dL7Xe+mtB6zUMumCLZUoWrfCWWFv88LwWY/nsUsKQrGnEwjCaVS4U+n8rSuSqluiPnjSlrWM0KmRuKBoI1VPRjYXLr76JVLwljiKPgVnjjSkvjpIM/7N8IpUaU+amNng7sz4GKULxfzcKOd2LiNUKc2kEDFYdNqGHGYbxGtujl9lPI1pGi9zYB2mRE8juTSmJhBRmgicyGTXbke8OX+3D2aOyYDX0TxfeeBClfD7wUlPuT3NGGkjPPtWGxMF/mg/b/E5WHj89uEEzHoyXk7TqEwZ7zUcD1Lw9JhXn4R+XzPewxZUuOR6Ug0rg49cGuUTYTsk/wywZBw9Y+rB3/Bsg=
  file: ./app/build/outputs/apk/release/app-release-unsigned.apk
  skip_cleanup: true
  on:
    branch: master
