language: android
dist: trusty
android:
  components:
    - build-tools-29.0.3
    - android-29
before-script:
  - chmod +x ./gradlew
script:
  - ./gradlew build
  - if [ "$TRAVIS_BRANCH" = "develop" ]; then ./gradlew sonarqube; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then 
        ./gradlew assembleRelease; 
        git config --global user.email "deploy@travis-ci.com"
        git config --global user.name "Travis CI Deploy"
        export GIT_TAG=1.0.$TRAVIS_BUILD_NUMBER
        git tag "$GIT_TAG" -a -m "Despliegue desde Travis con build numero $TRAVIS_BUILD_NUMBER";
    fi
deploy:
  provider: releases
  api_key:
    secure: Yt6pKmlfL/XSb2UBGn/XaLGZa9eyqIw0MDdLP1/GQjW6Z0Nji9sldL0k0ONJGlUshl2zJr+BEs4upaM3RkKfbFpIdkAwREW55e0X7+QWAZnFWu2oGm2mTwD1dNHh5l2K5YEIEyXLVa+7naDhLrF06peN8+nGnctuv9YabxXYmMmcoeilkqHCZ+2a9NDSKCdRmv+A5znSFoP+C7qwJdPu1BfhQbZ2AglbJWRTmmUm3tAydplUJNKX332naHHJZqqDKsIkOxBZsCBdNgc+bJOM5XLwfyIpzhPSnyqy2HzyLR25pvQlMjSvkxWpiJ4dCVQYsirF77v8BvIqa1wYLYFDcCdqtvZAZ5T0WUG45GNFuBOrqzl1idJR5jrmQWgksq9FYYtyWJiUio96ifrwmDV67KnUuy77Xfycjqd1rM7J6uxK7/W/xInrg2+l2BhByNch1fBwXiYFdXvej3mFRlTT+LVxry5sCdncqoCoiALm6hiYQ+I8JufZhv6Zoo51kroj6HSH8aX8bXdj9oewUZtoOtSI4/6mX6MoBSZjVqfzqGKBmk3CZsv6XPe0UZS2czMtD6s73K4ADZYaVDz2zFmc4UDLtjFLrwqBMLgaoyOZ8UJR4BKvVI/P51BKAy9LomlN92+JRlDRP8pCkNKHGnunxNnwbalB8NTabQv4wGEwtP4=
  file: app/builds/outputs/apk/release/app-release-unsigned.apk
  skip_cleanup: true
  on:
    branch: master